# Run tests in various tox environments.
name: tests

on:
  # NOTE(vytas): Trigger the tests workflow on push or pull request
  #   (pull requests only for the master branch for now).
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  run-tox:
    name: tox -e ${{ matrix.tox.env }}${{ matrix.tox.platform-label || '' }}
    runs-on: ${{ matrix.tox.os || matrix.default-os }}
    strategy:
      fail-fast: false
      matrix:
        default-os:
          - "ubuntu-22.04"
        python-version:
          - "3.12"
        tox:
          # TODO(vytas): Something is not working correctly with the
          #   newly released Firefox 131.0, SeleniumBase, and our tests.
          - env: "e2e_firefox"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        # NOTE(vytas): Work around
        #   https://github.com/codecov/codecov-action/issues/190
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.tox.python-version || matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade coverage setuptools tox wheel
          python --version
          pip --version
          tox --version
          coverage --version
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Run tox
        run: tox -e ${{ matrix.tox.env }}
